#!/usr/bin/env bash
#
# Build the site locally and publish it to the `deploy` branch, which cPanel
# checks out. This is the authoritative deploy path — GitHub Actions only runs
# tests; it does not touch `deploy`.
#
#   cd website && pnpm deploy            # test, build, publish
#   cd website && pnpm deploy --no-test  # skip the suite (not recommended)
#
# The branch is an orphan: every publish replaces it wholesale with the
# contents of dist/, so it never accumulates history or stale files.

set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(git rev-parse --show-toplevel)"
DEPLOY_PATH="/home2/safecode/kinnav.com/"
RUN_TESTS=1

for arg in "$@"; do
  case "$arg" in
    --no-test) RUN_TESTS=0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

# The deploy commit records which source commit it came from, so it has to be a
# commit that exists. A dirty tree would make that reference a lie.
if [ -n "$(git status --porcelain -- . )" ]; then
  echo "website/ has uncommitted changes — commit them first so the deploy" >&2
  echo "commit can name the source it was built from." >&2
  git status --short -- .
  exit 1
fi

SOURCE_SHA="$(git rev-parse HEAD)"
REMOTE_URL="${REMOTE_URL:-$(git remote get-url --push origin)}"

if [ "$RUN_TESTS" -eq 1 ]; then
  echo "==> lint"
  pnpm lint
  echo "==> test"
  pnpm test
fi

echo "==> build"
rm -rf dist
# NODE_ENV must be production or React ships its development build.
NODE_ENV=production pnpm exec vite build

echo "==> deployment manifest"
cat > dist/.cpanel.yml <<EOF
---
# Generated by website/scripts/publish-deploy.sh — do not edit by hand.
deployment:
  tasks:
    - export DEPLOYPATH=${DEPLOY_PATH}
    # Clear old content-hashed bundles so they don't accumulate.
    - /bin/rm -rf \$DEPLOYPATH/assets
    # Copy the site but never .git or this manifest: serving .git would
    # publish the whole repository history.
    - /usr/bin/rsync -a --exclude '.git/' --exclude '.cpanel.yml' ./ \$DEPLOYPATH
EOF

# Sanity checks — these are the failures that only show up once the site is
# live, so they are worth catching before the push rather than after.
for required in index.html .htaccess .cpanel.yml api/contact.php api/.htaccess; do
  [ -e "dist/$required" ] || { echo "missing from build: $required" >&2; exit 1; }
done
if find dist -name '*.map' -o -name '.env*' | grep -q .; then
  echo "refusing to publish: build contains source maps or env files" >&2
  exit 1
fi

echo "==> publish to deploy"
(
  cd dist
  rm -rf .git
  git init -q
  git config user.name "$(git -C "$REPO_ROOT" config user.name)"
  git config user.email "$(git -C "$REPO_ROOT" config user.email)"
  git checkout -q -b deploy
  git add -A
  git commit -q -m "Build website from ${SOURCE_SHA}"
  git push --force -q "$REMOTE_URL" deploy:deploy
  echo "published $(git ls-files | wc -l | tr -d ' ') files from ${SOURCE_SHA:0:7}"
  rm -rf .git
)

cat <<'DONE'

Published. Now in cPanel:
  Git Version Control -> Kinnav Website -> Manage
  -> Update from Remote -> Deploy HEAD Commit

Then verify:
  curl -I https://kinnav.com/about          # 200
  curl -I https://kinnav.com/.git/config    # 403 or 404, never 200
DONE
