#!/usr/bin/env bash
#
# Build the site locally and publish it to the `deploy` branch, which cPanel
# checks out. This is the authoritative deploy path — GitHub Actions only runs
# tests; it does not touch `deploy`.
#
#   cd website && pnpm deploy            # test, build, publish
#   cd website && pnpm deploy --no-test  # skip the suite (not recommended)
#
# The branch is an orphan: every publish replaces it wholesale with the
# contents of dist/, so it never accumulates history or stale files.

set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(git rev-parse --show-toplevel)"
DEPLOY_PATH="/home2/safecode/kinnav.com/"
RUN_TESTS=1

for arg in "$@"; do
  case "$arg" in
    --no-test) RUN_TESTS=0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

# The deploy commit records which source commit it came from, so it has to be a
# commit that exists. A dirty tree would make that reference a lie.
if [ -n "$(git status --porcelain -- . )" ]; then
  echo "website/ has uncommitted changes — commit them first so the deploy" >&2
  echo "commit can name the source it was built from." >&2
  git status --short -- .
  exit 1
fi

SOURCE_SHA="$(git rev-parse HEAD)"
REMOTE_URL="${REMOTE_URL:-$(git remote get-url --push origin)}"

if [ "$RUN_TESTS" -eq 1 ]; then
  echo "==> lint"
  pnpm lint
  echo "==> test"
  pnpm test
fi

echo "==> build"
rm -rf dist
# NODE_ENV must be production or React ships its development build.
NODE_ENV=production pnpm exec vite build

# Bake the static routes into real HTML. Without this every URL serves the same
# empty SPA shell, and Google Play's automated check of the privacy-policy URL
# finds no policy — see scripts/prerender.mjs.
echo "==> prerender"
NODE_ENV=production node scripts/prerender.mjs

echo "==> deployment manifest"
cat > dist/.cpanel.yml <<EOF
---
# Generated by website/scripts/publish-deploy.sh — do not edit by hand.
deployment:
  tasks:
    - export DEPLOYPATH=${DEPLOY_PATH}
    # If the repository IS the document root, the checkout already is the live
    # site — there is nothing to copy, and the next task would delete the
    # checkout's own assets directory. Succeed and stop.
    - if [ "\$(pwd -P)" = "\$(cd \$DEPLOYPATH 2>/dev/null && pwd -P)" ]; then echo 'Repository is the document root: the checkout is already live, nothing to copy.'; exit 0; fi
    # Clear old content-hashed bundles so they don't accumulate.
    - /bin/rm -rf \$DEPLOYPATH/assets
    # Copy the site but never .git or this manifest: serving .git would
    # publish the whole repository history.
    - rsync -a --exclude '.git/' --exclude '.cpanel.yml' ./ \$DEPLOYPATH
EOF

# Sanity checks — these are the failures that only show up once the site is
# live, so they are worth catching before the push rather than after.
for required in index.html .htaccess .cpanel.yml api/contact.php api/.htaccess \
                privacy/index.html terms/index.html; do
  [ -e "dist/$required" ] || { echo "missing from build: $required" >&2; exit 1; }
done

# The store listings point at /privacy and /terms. Publishing those as empty
# shells is what gets a submission rejected, so prove the text is really there
# rather than trusting that the prerender ran.
for page in privacy terms; do
  grep -qi "$page" "dist/$page/index.html" \
    || { echo "refusing to publish: dist/$page/index.html has no '$page' text" >&2; exit 1; }
done
if find dist -name '*.map' -o -name '.env*' | grep -q .; then
  echo "refusing to publish: build contains source maps or env files" >&2
  exit 1
fi
# The handler's rate-limit counters (hashed visitor IPs) are a server runtime
# artefact. vite.config.js strips them, so reaching here means something else
# put them in the build — publishing them would leak them.
if [ -e dist/api/.state ]; then
  echo "refusing to publish: build contains api/.state (rate-limit counters)" >&2
  exit 1
fi

# The server keeps its checkout in the document root and updates with
# `git pull` (or cPanel's "Update from Remote"), so the deploy branch must have
# continuous history — a force-pushed orphan commit would make every pull fail
# with "refusing to merge unrelated histories". So: clone the existing branch,
# replace its contents with this build, and fast-forward it.
echo "==> publish to deploy"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

if git ls-remote --exit-code --heads "$REMOTE_URL" deploy >/dev/null 2>&1; then
  git clone -q --branch deploy --single-branch "$REMOTE_URL" "$WORK"
else
  echo "    deploy branch does not exist yet; creating it"
  git init -q "$WORK"
  git -C "$WORK" checkout -q -b deploy
fi

git -C "$WORK" config user.name "$(git -C "$REPO_ROOT" config user.name)"
git -C "$WORK" config user.email "$(git -C "$REPO_ROOT" config user.email)"

# --delete so files removed from the build disappear from the branch too.
# .well-known is excluded because AutoSSL owns it on the server; it must never
# be tracked, and .gitignore below keeps `git clean` from removing it.
rsync -a --delete --exclude '.git/' --exclude '.well-known/' dist/ "$WORK/"

cat > "$WORK/.gitignore" <<'EOF'
# AutoSSL writes its domain-validation files here on the server. It is not part
# of the build and must survive every deploy.
.well-known/
EOF

if git -C "$WORK" diff --quiet HEAD -- 2>/dev/null && [ -z "$(git -C "$WORK" status --porcelain)" ]; then
  echo "    deploy branch already matches this build; nothing to push"
else
  git -C "$WORK" add -A
  git -C "$WORK" commit -q -m "Build website from ${SOURCE_SHA}"

  # Pushing through a corporate proxy drops connections occasionally
  # ("bad record mac", "unexpected disconnect"); a retry clears it.
  pushed=0
  for attempt in 1 2 3; do
    if git -C "$WORK" push -q "$REMOTE_URL" deploy:deploy; then
      pushed=1
      break
    fi
    echo "push attempt ${attempt} failed; retrying in $((attempt * 5))s" >&2
    sleep $((attempt * 5))
  done
  [ "$pushed" -eq 1 ] || { echo "push failed after 3 attempts" >&2; exit 1; }
  echo "    published $(git -C "$WORK" ls-files | wc -l | tr -d ' ') files from ${SOURCE_SHA:0:7}"
fi

cat <<'DONE'

Published. Now in cPanel:
  Git Version Control -> Kinnav Website -> Manage
  -> Update from Remote -> Deploy HEAD Commit

Then verify:
  curl -I https://kinnav.com/about          # 200
  curl -I https://kinnav.com/.git/config    # 403 or 404, never 200
DONE
